### ISSUE TITLE
Missing sed target in ai.js

### ISSUE THREAD

**Issue by danielrhodeswarp** [adhorn/poliko#3]
Hello Adhorn,

Not a biggie but I feel like "IdentityPoolId" in ai.js should be "REPLACE_ME" (which setup_cognito.sh certainly seems to be looking for) rater than a literal pool ID.

This is a very nice demo BTW which I learned about from the recent AWS Learning Week; thanks!

Kind regards,
Daniel

**Comment by adhorn** [comment]
Thanks! Sorry I didn't notice your comment before. I have now merged you PR. Thank you!
